image: node:10-alpine

stages:
  - package

package:
  stage: package
  before_script:
    - npm install -g vsce
    - npm install -g typescript
    - npm install
  cache:
    paths:
      - node_modules/
  script:
    - vsce package
  artifacts:
    paths:
      - code-stats-vscode-*.vsix

